# Настройки плагина AuctionShop
# Валюта хранится во внутренней встроенной экономике (файл balances.yml)

# Минимальная цена лота на аукционе
min-auction-price: 1

# Максимальная цена лота на аукционе
max-auction-price: 1000000
